import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from '@/app/components/Navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "devjaishoy - Full-stack Developer & Freelancer",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className="bg-zinc-950 text-zinc-100 antialiased">
        <Navbar />
        <main className="pt-[60px]">
          {children}
        </main>
        <footer className="border-t border-zinc-900 py-8 mt-auto">
          <div className="max-w-5xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-zinc-600 text-xs">© 2025 devjaishoy. All rights reserved.</p>
            <div className="flex items-center gap-5">
              <a href="/privacy" className="text-zinc-600 hover:text-zinc-400 text-xs transition">
                Privacy Policy
              </a>
              <a href="/chat" className="text-zinc-600 hover:text-zinc-400 text-xs transition">
                Contact
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
